# Generated by Django 3.2.16 on 2023-02-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230130_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(default='placeId', max_length=200, verbose_name='placeId'),
            preserve_default=False,
        ),
    ]
