# Generated by Django 3.2.16 on 2023-02-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_image_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='detailsUrl',
        ),
    ]
